// features/bets/mock-data.ts
// Realistic mock data for the betting experience (My Bets, cash out).

import { createMockMatch, mockMarkets } from "@/features/sportsbook/mock-data";
import type { BetSelection, Match, Market, Selection } from "@/features/sportsbook/types";
import type { PlacedBet } from "@/types/bets";

const now = Date.now();
const hoursAgo = (h: number) => new Date(now - h * 3_600_000).toISOString();
const daysAgo = (d: number) => new Date(now - d * 86_400_000).toISOString();

const makeSelection = (
  match: Match,
  market: Market,
  sel: Selection
): BetSelection => ({
  id: `${match.id}-${market.id}-${sel.id}`,
  matchId: match.id,
  marketId: market.id,
  selectionId: sel.id,
  match,
  market,
  selection: sel,
});

const mHome = createMockMatch({
  id: "b1",
  leagueId: "l1",
  homeTeam: {
    id: "t1",
    name: "Manchester United",
    shortName: "MUN",
    logo: "🟥",
  },
  awayTeam: {
    id: "t2",
    name: "Liverpool",
    shortName: "LIV",
    logo: "🔴",
  },
  status: "live",
  liveMinute: 72,
  score: { home: 2, away: 1 },
  isLive: true,
});

const mAway = createMockMatch({
  id: "b2",
  leagueId: "l2",
  homeTeam: {
    id: "t3",
    name: "Real Madrid",
    shortName: "RMA",
    logo: "⚪",
  },
  awayTeam: {
    id: "t4",
    name: "Barcelona",
    shortName: "BAR",
    logo: "🔵",
  },
  status: "live",
  liveMinute: 55,
  score: { home: 1, away: 1 },
  isLive: true,
});

const mScheduled = createMockMatch({
  id: "b3",
  leagueId: "l3",
  homeTeam: {
    id: "t5",
    name: "Lakers",
    shortName: "LAL",
    logo: "🟡",
  },
  awayTeam: {
    id: "t6",
    name: "Celtics",
    shortName: "BOS",
    logo: "🟢",
  },
  status: "scheduled",
  startTime: new Date(now + 7_200_000).toISOString(),
});

export const mockPlacedBets: PlacedBet[] = [
  {
    id: "bet_1",
    ticketNumber: "TN-9F3A21C7",
    selections: [makeSelection(mHome, mockMarkets[0], mockMarkets[0].selections[0])],
    betType: "single",
    totalOdds: 2.1,
    stake: 50,
    potentialWin: 105,
    status: "open",
    placedAt: hoursAgo(1),
    currency: "USD",
    cashOut: {
      available: true,
      fullValue: 78.4,
      minPartial: 10,
      maxPartial: 78.4,
      settledAmount: 0,
      confidence: 0.62,
    },
    selectionResults: [{ selectionId: "s1", outcome: "pending" }],
  },
  {
    id: "bet_2",
    ticketNumber: "TN-7B2E55D1",
    selections: [makeSelection(mAway, mockMarkets[2], mockMarkets[2].selections[0])],
    betType: "single",
    totalOdds: 1.75,
    stake: 25,
    potentialWin: 43.75,
    status: "open",
    placedAt: hoursAgo(2),
    currency: "USD",
    cashOut: {
      available: true,
      fullValue: 31.2,
      minPartial: 5,
      maxPartial: 31.2,
      settledAmount: 0,
      confidence: 0.55,
    },
    selectionResults: [{ selectionId: "s6", outcome: "pending" }],
  },
  {
    id: "bet_3",
    ticketNumber: "TN-4C8D90A3",
    selections: [
      makeSelection(mHome, mockMarkets[0], mockMarkets[0].selections[0]),
      makeSelection(mAway, mockMarkets[0], mockMarkets[0].selections[2]),
    ],
    betType: "accumulator",
    totalOdds: 6.72,
    stake: 20,
    potentialWin: 134.4,
    status: "open",
    placedAt: hoursAgo(3),
    currency: "USD",
    cashOut: {
      available: true,
      fullValue: 54.1,
      minPartial: 5,
      maxPartial: 54.1,
      settledAmount: 0,
      confidence: 0.4,
    },
    selectionResults: [
      { selectionId: "s1", outcome: "pending" },
      { selectionId: "s3", outcome: "pending" },
    ],
  },
  {
    id: "bet_4",
    ticketNumber: "TN-1A6F77B9",
    selections: [makeSelection(mScheduled, mockMarkets[0], mockMarkets[0].selections[0])],
    betType: "single",
    totalOdds: 2.1,
    stake: 100,
    potentialWin: 210,
    status: "open",
    placedAt: hoursAgo(4),
    currency: "USD",
    cashOut: {
      available: true,
      fullValue: 99.5,
      minPartial: 10,
      maxPartial: 99.5,
      settledAmount: 0,
      confidence: 0.5,
    },
    selectionResults: [{ selectionId: "s1", outcome: "pending" }],
  },
  {
    id: "bet_5",
    ticketNumber: "TN-2D5C11E8",
    selections: [makeSelection(mHome, mockMarkets[1], mockMarkets[1].selections[0])],
    betType: "single",
    totalOdds: 1.85,
    stake: 40,
    potentialWin: 74,
    status: "won",
    placedAt: daysAgo(2),
    settledAt: daysAgo(1),
    currency: "USD",
    returnedAmount: 114,
    selectionResults: [{ selectionId: "s4", outcome: "won" }],
  },
  {
    id: "bet_6",
    ticketNumber: "TN-8E9B33F2",
    selections: [makeSelection(mAway, mockMarkets[0], mockMarkets[0].selections[2])],
    betType: "single",
    totalOdds: 3.2,
    stake: 15,
    potentialWin: 48,
    status: "lost",
    placedAt: daysAgo(3),
    settledAt: daysAgo(2),
    currency: "USD",
    returnedAmount: 0,
    selectionResults: [{ selectionId: "s3", outcome: "lost" }],
  },
  {
    id: "bet_7",
    ticketNumber: "TN-3F1A66C4",
    selections: [
      makeSelection(mHome, mockMarkets[0], mockMarkets[0].selections[0]),
      makeSelection(mAway, mockMarkets[2], mockMarkets[2].selections[1]),
    ],
    betType: "accumulator",
    totalOdds: 4.2,
    stake: 30,
    potentialWin: 126,
    status: "won",
    placedAt: daysAgo(5),
    settledAt: daysAgo(4),
    currency: "USD",
    returnedAmount: 156,
    selectionResults: [
      { selectionId: "s1", outcome: "won" },
      { selectionId: "s7", outcome: "won" },
    ],
  },
  {
    id: "bet_8",
    ticketNumber: "TN-6B4D22A1",
    selections: [makeSelection(mScheduled, mockMarkets[2], mockMarkets[2].selections[0])],
    betType: "single",
    totalOdds: 1.75,
    stake: 60,
    potentialWin: 105,
    status: "cancelled",
    placedAt: daysAgo(6),
    settledAt: daysAgo(6),
    currency: "USD",
    returnedAmount: 60,
    selectionResults: [{ selectionId: "s6", outcome: "void" }],
  },
  {
    id: "bet_9",
    ticketNumber: "TN-5C7E19B6",
    selections: [makeSelection(mHome, mockMarkets[0], mockMarkets[0].selections[0])],
    betType: "single",
    totalOdds: 2.1,
    stake: 80,
    potentialWin: 168,
    status: "partially_cashed_out",
    placedAt: daysAgo(1),
    settledAt: hoursAgo(5),
    currency: "USD",
    returnedAmount: 95,
    cashOut: {
      available: true,
      fullValue: 22.3,
      minPartial: 5,
      maxPartial: 22.3,
      settledAmount: 95,
      confidence: 0.7,
    },
    selectionResults: [{ selectionId: "s1", outcome: "pending" }],
  },
];
