// features/wallet/mock-data.ts
// Realistic mock data for the wallet experience.

import type {
  WalletBalance,
  PaymentMethod,
  BankAccount,
  WalletTransaction,
  Bonus,
} from "@/types/wallet";

export const mockWalletBalance: WalletBalance = {
  available: 1250.5,
  bonus: 200,
  locked: 75,
  pendingWithdrawals: 150,
  currency: "USD",
};

export const mockPaymentMethods: PaymentMethod[] = [
  {
    id: "pm_card",
    type: "card",
    label: "Visa ending 4242",
    detail: "Expires 09/27",
    icon: "💳",
    min: 10,
    max: 5000,
    fee: 0,
    processingTime: "Instant",
    currency: "USD",
    isDefault: true,
  },
  {
    id: "pm_paypal",
    type: "paypal",
    label: "PayPal",
    detail: "john.doe@example.com",
    icon: "🅿️",
    min: 10,
    max: 2000,
    fee: 0,
    processingTime: "Instant",
    currency: "USD",
  },
  {
    id: "pm_skril",
    type: "skrill",
    label: "Skrill",
    detail: "john.doe@example.com",
    icon: "🅂",
    min: 10,
    max: 2000,
    fee: 1.5,
    processingTime: "Instant",
    currency: "USD",
  },
  {
    id: "pm_crypto",
    type: "crypto",
    label: "Bitcoin",
    detail: "BTC wallet",
    icon: "₿",
    min: 20,
    max: 10000,
    fee: 0,
    processingTime: "10-30 min",
    currency: "USD",
  },
];

export const mockBankAccounts: BankAccount[] = [
  {
    id: "ba_1",
    accountName: "John Doe",
    bankName: "Chase Bank",
    last4: "4821",
    ibanLast4: "3391",
    country: "United States",
    isDefault: true,
  },
  {
    id: "ba_2",
    accountName: "John Doe",
    bankName: "Bank of America",
    last4: "7714",
    ibanLast4: "8820",
    country: "United States",
  },
];

const now = Date.now();
const minutesAgo = (m: number) => new Date(now - m * 60_000).toISOString();
const daysAgo = (d: number) => new Date(now - d * 86_400_000).toISOString();

export const mockTransactions: WalletTransaction[] = [
  {
    id: "tx_1",
    type: "deposit",
    amount: 500,
    currency: "USD",
    status: "completed",
    timestamp: minutesAgo(35),
    description: "Deposit via Visa",
    method: "Visa ending 4242",
    reference: "DEP-882910",
  },
  {
    id: "tx_2",
    type: "bet_won",
    amount: 105,
    currency: "USD",
    status: "completed",
    timestamp: minutesAgo(120),
    description: "Won: Man United vs Liverpool",
    reference: "WIN-4412",
  },
  {
    id: "tx_3",
    type: "bet_placed",
    amount: 50,
    currency: "USD",
    status: "completed",
    timestamp: minutesAgo(140),
    description: "Bet: Lakers vs Celtics",
    reference: "BET-3391",
  },
  {
    id: "tx_4",
    type: "withdrawal",
    amount: 150,
    currency: "USD",
    status: "pending",
    timestamp: minutesAgo(200),
    description: "Withdrawal to Chase Bank",
    method: "Chase Bank",
    reference: "WD-2208",
  },
  {
    id: "tx_5",
    type: "bonus",
    amount: 200,
    currency: "USD",
    status: "completed",
    timestamp: daysAgo(2),
    description: "Welcome Bonus credited",
    reference: "BNS-1002",
  },
  {
    id: "tx_6",
    type: "deposit",
    amount: 1000,
    currency: "USD",
    status: "failed",
    timestamp: daysAgo(3),
    description: "Deposit via PayPal (declined)",
    method: "PayPal",
    reference: "DEP-7710",
  },
  {
    id: "tx_7",
    type: "bet_lost",
    amount: 25,
    currency: "USD",
    status: "completed",
    timestamp: daysAgo(4),
    description: "Lost: Djokovic vs Alcaraz",
    reference: "BET-2988",
  },
  {
    id: "tx_8",
    type: "refund",
    amount: 30,
    currency: "USD",
    status: "completed",
    timestamp: daysAgo(5),
    description: "Cancelled bet refund",
    reference: "REF-1102",
  },
  {
    id: "tx_9",
    type: "withdrawal",
    amount: 300,
    currency: "USD",
    status: "completed",
    timestamp: daysAgo(7),
    description: "Withdrawal to Bank of America",
    method: "Bank of America",
    reference: "WD-1902",
  },
  {
    id: "tx_10",
    type: "deposit",
    amount: 250,
    currency: "USD",
    status: "completed",
    timestamp: daysAgo(10),
    description: "Deposit via Skrill",
    method: "Skrill",
    reference: "DEP-6620",
  },
];

export const mockBonuses: Bonus[] = [
  {
    id: "bn_1",
    title: "Welcome Bonus",
    description: "100% match up to $200 on your first deposit",
    amount: 200,
    currency: "USD",
    status: "active",
    wageringRequired: 4000,
    wageringCompleted: 2450,
    startDate: daysAgo(2),
    expiryDate: daysAgo(-28),
    code: "WELCOME200",
  },
  {
    id: "bn_2",
    title: "Free Bet Club",
    description: "$10 free bet every weekend for active players",
    amount: 10,
    currency: "USD",
    status: "active",
    wageringRequired: 100,
    wageringCompleted: 40,
    startDate: daysAgo(1),
    expiryDate: daysAgo(-6),
  },
  {
    id: "bn_3",
    title: "Acca Insurance",
    description: "Stake returned as bonus if one leg loses",
    amount: 50,
    currency: "USD",
    status: "completed",
    wageringRequired: 500,
    wageringCompleted: 500,
    startDate: daysAgo(20),
    expiryDate: daysAgo(-10),
  },
  {
    id: "bn_4",
    title: "Reload Bonus",
    description: "50% reload up to $100 every Friday",
    amount: 100,
    currency: "USD",
    status: "expired",
    wageringRequired: 2000,
    wageringCompleted: 850,
    startDate: daysAgo(40),
    expiryDate: daysAgo(13),
  },
];
